# Generated by Django 3.1.1 on 2020-09-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200929_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_pizza',
            name='Foto',
            field=models.ImageField(default=0, upload_to='fotos/'),
            preserve_default=False,
        ),
    ]
